Repository multiversx/mx-api-service, pull requests merged in 2022-10, with the labels that each got.

#831 Set node offline if no online property set
  src/endpoints/nodes/node.service.ts
Labels: bugfix

#829 transactions searchable by collection/nft
  src/endpoints/collections/collection.controller.ts
  src/endpoints/nfts/nft.controller.ts
Labels: feature

#833 add istransferAffected spec test
  src/test/data/esdt/nft/nft.example.ts
  src/test/integration/graphql/nfts.graph-spec.ts
  src/test/integration/services/nft.e2e-spec.ts
  src/test/integration/services/process.nfts.e2e-spec.ts
Labels: test

#834 Do not apply transfer affected on multiple nfts endpoint
  src/endpoints/nfts/nft.service.ts
  src/test/integration/services/nft.e2e-spec.ts
Labels: ignore-for-release

#835 Searchable nft traits
  package-lock.json
  package.json
  src/common/indexer/elastic/elastic.indexer.helper.ts
  src/endpoints/nfts/entities/nft.filter.ts
  src/endpoints/nfts/nft.controller.ts
Labels: feature

#836 transaction filter allow sender receiver to be metachain
  package-lock.json
  package.json
  src/endpoints/transactions/transaction.controller.ts
  src/test/integration/controllers/transactions.controller.e2e-spec.ts
Labels: feature, test

#838 Collection NFTs trait filter
  src/common/indexer/elastic/elastic.indexer.helper.ts
  src/common/indexer/entities/collection.trait.summary.attribute.ts
  src/common/indexer/entities/collection.trait.summary.ts
  src/common/indexer/entities/collection.ts
  src/endpoints/collections/collection.controller.ts
  src/endpoints/collections/collection.service.ts
  src/endpoints/collections/entities/collection.trait.attribute.ts
  src/endpoints/collections/entities/collection.trait.ts
  src/endpoints/collections/entities/nft.collection.ts
  src/graphql/schema/schema.gql
  src/test/integration/controllers/collections.controller.e2e-spec.ts
Labels: test

#837 refactor transaction service unit tests
  src/test/integration/services/transactions.e2e-spec.ts
Labels: test

#840 filter nfts by nonce before after
  src/common/indexer/elastic/elastic.indexer.helper.ts
  src/endpoints/collections/collection.controller.ts
  src/endpoints/nfts/entities/nft.filter.ts
  src/graphql/entities/nft/nft.input.ts
  src/graphql/schema/schema.gql
  src/test/integration/graphql/nfts.graph-spec.ts
Labels: feature, test

#844 add nonce after nonce before spec tests
  src/test/integration/services/nft.e2e-spec.ts
Labels: test

#843 Two way matching between provider and keybase
  src/endpoints/providers/provider.service.ts
Labels: feature

#845 add collections service / proxy controller spec tests
  src/test/integration/controllers/proxy.controller.e2e-spec.ts
  src/test/integration/services/collections.e2e-spec.ts
Labels: test

#854 NFT collection custom ranks in assets
  src/common/assets/assets.service.ts
  src/common/assets/entities/nft.rank.algorithm.ts
  src/common/assets/entities/nft.rank.ts
  src/common/assets/entities/token.assets.ts
  src/endpoints/collections/collection.controller.ts
  src/endpoints/collections/collection.service.ts
  src/graphql/entities/nft.collection/nft.collection.query.ts
  src/graphql/schema/schema.gql
  src/utils/cache.info.ts
Labels: feature

#851 add transfers query
  src/endpoints/transactions/entities/transaction.ts
  src/endpoints/transactions/entities/transaction.type.ts
  src/graphql/entities/graphql.services.module.ts
  src/graphql/entities/transfers/transfers.input.ts
  src/graphql/entities/transfers/transfers.module.ts
  src/graphql/entities/transfers/transfers.query.ts
  src/graphql/entities/transfers/transfers.resolver.ts
  src/graphql/schema/schema.gql
Labels: feature

#858 SERVICES-795 rename scResults queries
  src/graphql/entities/smart.contract.result/smart.contract.result.query.ts
  src/graphql/schema/schema.gql
  src/test/integration/graphql/smart.contract.result.graph-spec.ts
Labels: refactoring

#860 Nft rarities ES mappings
  src/common/assets/entities/nft.rank.algorithm.ts
  src/common/assets/entities/token.assets.ts
  src/common/indexer/elastic/elastic.indexer.service.ts
  src/endpoints/collections/collection.controller.ts
  src/endpoints/collections/entities/sort.collection.nfts.ts
  src/endpoints/nfts/entities/nft.filter.ts
  src/endpoints/nfts/entities/nft.rarities.ts
  src/endpoints/nfts/entities/nft.rarity.ts
  src/endpoints/nfts/entities/nft.ts
  src/endpoints/nfts/nft.service.ts
  src/graphql/schema/schema.gql
  src/test/data/esdt/nft/nft.example.ts
  src/test/integration/services/nft.e2e-spec.ts
  src/test/integration/services/process.nfts.e2e-spec.ts
Labels: feature

#861 add senders filter to tranfers
  src/common/indexer/elastic/elastic.indexer.helper.ts
  src/endpoints/transactions/entities/transaction.filter.ts
  src/endpoints/transfers/transfer.controller.ts
Labels: feature

#862 label account contracts endpoint
  src/common/indexer/entities/sc.deploy.ts
  src/endpoints/accounts/account.service.ts
  src/endpoints/accounts/entities/deployed.contract.ts
Labels: feature

#863 Identity apr take queued nodes into account
  src/endpoints/identities/entities/stake.info.ts
  src/endpoints/identities/identities.service.ts
Labels: bugfix

#842 add herotag details in transactions
  config/config.devnet.yaml
  config/config.e2e-mocked.mainnet.yaml
  config/config.e2e.mainnet.yaml
  config/config.mainnet.yaml
  config/config.testnet.yaml
  src/common/api-config/api.config.service.ts
  src/endpoints/accounts/account.controller.ts
  src/endpoints/accounts/account.module.ts
  src/endpoints/accounts/account.service.ts
  src/endpoints/accounts/entities/account.detailed.ts
  src/endpoints/collections/collection.controller.ts
  src/endpoints/nfts/nft.controller.ts
  src/endpoints/tokens/token.controller.ts
  src/endpoints/transactions/entities/transaction.operation.ts
  src/endpoints/transactions/entities/transaction.ts
  src/endpoints/transactions/entities/transactions.query.options.ts
  src/endpoints/transactions/transaction.controller.ts
  src/endpoints/transactions/transaction.module.ts
  src/endpoints/transactions/transaction.service.ts
  src/endpoints/transfers/transfer.controller.ts
  src/endpoints/transfers/transfer.service.ts
  src/endpoints/usernames/username.controller.ts
  src/endpoints/usernames/username.service.ts
  src/graphql/entities/transaction.detailed/transaction.detailed.input.ts
  src/graphql/entities/transaction.detailed/transaction.detailed.query.ts
  src/graphql/entities/transfers/transfers.input.ts
  src/graphql/entities/transfers/transfers.query.ts
  src/graphql/entities/username/username.input.ts
  src/graphql/entities/username/username.query.ts
  src/graphql/schema/schema.gql
  src/test/integration/controllers/username.controller.e2e-spec.ts
  src/test/integration/graphql/username.graph-spec.ts
  src/test/integration/services/accounts.e2e-spec.ts
  src/test/integration/services/api.config.e2e-spec.ts
  src/test/integration/services/transfers.e2e-spec.ts
  src/test/integration/services/username.e2e-spec.ts
  src/test/unit/utils/transaction.utils.spec.ts
  src/utils/cache.info.ts
Labels: feature

#864 Add support for multiple senders in account transfers endpoint
  src/endpoints/accounts/account.controller.ts
Labels: feature

#869 Fix result when no token roles
  src/endpoints/tokens/token.service.ts
  src/test/integration/controllers/tokens.controller.e2e-spec.ts
  src/test/integration/services/tokens.e2e-spec.ts
Labels: bugfix

#865 Refresh collection ranks in cache warmer
  src/crons/cache.warmer/cache.warmer.service.ts
  src/endpoints/collections/collection.controller.ts
Labels: bugfix
