Repository multiversx/mx-api-service, pull requests merged in 2022-12, with the labels that each got.

#897 Unified Tokens & MetaESDTs
  src/common/indexer/elastic/elastic.indexer.helper.ts
  src/common/indexer/elastic/elastic.indexer.service.ts
  src/common/indexer/entities/token.account.ts
  src/common/indexer/entities/token.data.ts
  src/common/indexer/entities/token.ts
  src/common/indexer/indexer.interface.ts
  src/common/indexer/indexer.service.ts
  src/crons/cache.warmer/cache.warmer.service.ts
  src/endpoints/accounts/account.controller.ts
  src/endpoints/accounts/account.module.ts
  src/endpoints/collections/collection.controller.ts
  src/endpoints/collections/collection.service.ts
  src/endpoints/collections/entities/collection.filter.ts
  src/endpoints/collections/entities/nft.collection.detailed.ts
  src/endpoints/collections/entities/nft.collection.role.ts
  src/endpoints/collections/entities/nft.collection.ts
  src/endpoints/collections/entities/nft.collection.with.roles.ts
  src/endpoints/esdt/entities/esdt.type.ts
  src/endpoints/esdt/esdt.address.service.ts
  src/endpoints/esdt/esdt.service.ts
  src/endpoints/network/network.module.ts
  src/endpoints/network/network.service.ts
  src/endpoints/nfts/entities/nft.filter.ts
  src/endpoints/tokens/entities/token.account.ts
  src/endpoints/tokens/entities/token.detailed.ts
  src/endpoints/tokens/entities/token.detailed.with.balance.ts
  src/endpoints/tokens/entities/token.filter.ts
  src/endpoints/tokens/entities/token.properties.ts
  src/endpoints/tokens/entities/token.roles.ts
  src/endpoints/tokens/entities/token.transfer.properties.ts
  src/endpoints/tokens/entities/token.ts
  src/endpoints/tokens/entities/token.type.ts
  src/endpoints/tokens/entities/token.with.balance.ts
  src/endpoints/tokens/entities/token.with.roles.filter.ts
  src/endpoints/tokens/entities/token.with.roles.ts
  src/endpoints/tokens/token.controller.ts
  src/endpoints/tokens/token.module.ts
  src/endpoints/tokens/token.service.ts
  src/endpoints/transactions/entities/transaction.operation.ts
  src/endpoints/transactions/transaction-action/recognizers/esdt/transaction.action.esdt.nft.recognizer.service.ts
  src/endpoints/transactions/transaction-action/recognizers/mex/mex.wrap.action.recognizer.service.ts
  src/graphql/entities/account.detailed/account.detailed.input.ts
  src/graphql/entities/account.detailed/account.detailed.resolver.ts
  src/graphql/entities/nft.collection/nft.collection.input.ts
  src/graphql/entities/nft.collection/nft.collection.query.ts
  src/graphql/schema/schema.gql
  src/test/integration/api/tokens.api-spec.ts
  src/test/integration/controllers/collections.controller.e2e-spec.ts
  src/test/integration/controllers/tokens.controller.e2e-spec.ts
  src/test/integration/graphql/collections,graph-spec.ts
  src/test/integration/services/collections.e2e-spec.ts
  src/test/integration/services/e2e-init.ts
  src/test/integration/services/esdt.address.e2e-spec.ts
  src/test/integration/services/esdt.e2e-spec.ts
  src/test/integration/services/nft.e2e-spec.ts
  src/test/integration/services/nft.extendedattributes.e2e-spec.ts
  src/test/integration/services/tokens.e2e-spec.ts
  src/test/mocks/tokens.mock.json
  src/test/unit/utils/transaction.utils.spec.ts
  src/utils/api.checker.ts
Labels: feature, test

#909 fix accounts unit tests from development branch
  src/test/integration/controllers/tokens.controller.e2e-spec.ts
  src/test/integration/services/dapp.config.e2e-spec.ts
  src/test/integration/services/nft.e2e-spec.ts
  src/test/unit/graphql/entities/account.detailed/account.detailed.resolver.spec.ts
  src/test/unit/utils/transaction.utils.spec.ts
Labels: test

#910 Do not compute scam info if withScamInfo parameter is false
  src/endpoints/nfts/entities/nft.query.options.ts
Labels: bugfix

#907 Fix xExchange queries
  src/endpoints/mex/entities/mex.economics.ts
  src/endpoints/mex/entities/mex.farm.ts
  src/endpoints/mex/entities/mex.settings.ts
  src/endpoints/mex/entities/mex.staking.proxy.ts
  src/endpoints/mex/mex.controller.ts
  src/endpoints/mex/mex.economics.service.ts
  src/endpoints/mex/mex.farm.service.ts
  src/endpoints/mex/mex.settings.service.ts
  src/endpoints/mex/mex.token.service.ts
  src/graphql/schema/schema.gql
Labels: bugfix

#918 Handle Inactive node status
  src/endpoints/nodes/node.service.ts
  src/test/integration/controllers/proxy.controller.e2e-spec.ts
  src/test/integration/controllers/tokens.controller.e2e-spec.ts
  src/test/integration/graphql/tokens.graph-spec.ts
  src/test/integration/services/providers.e2e-spec.ts
  src/test/integration/services/tokens.e2e-spec.ts
Labels: bugfix
