Repository multiversx/mx-api-service, pull requests merged in 2022-09, with the labels that each got.

#803 include metadata from the input image in the output when generating thumbnail
  src/queue.worker/nft.worker/queue/job-services/thumbnails/nft.thumbnail.service.ts
Labels: bugfix

#808 remove required parameters from swagger api
  src/endpoints/accounts/account.controller.ts
  src/endpoints/collections/collection.controller.ts
  src/endpoints/nfts/nft.controller.ts
  src/endpoints/tokens/token.controller.ts
  src/endpoints/transactions/transaction.controller.ts
Labels: refactoring

#810 add Id filter for mex/token enpoint
  src/endpoints/mex/mex.controller.ts
  src/endpoints/mex/mex.token.service.ts
Labels: feature

#806 Sort locked accounts by balance descending
  src/endpoints/tokens/token.service.ts
  src/test/integration/services/tokens.e2e-spec.ts
Labels: feature

#809 Logo resolver for tokens and collections
  src/common/assets/assets.service.ts
  src/endpoints/collections/collection.service.ts
  src/endpoints/esdt/esdt.service.ts
  src/endpoints/nfts/nft.service.ts
  src/endpoints/tokens/entities/token.logo.ts
  src/endpoints/tokens/token.controller.ts
  src/endpoints/tokens/token.service.ts
  src/endpoints/tokens/token.transfer.service.ts
Labels: feature

#812 Fix keybase & mex token fields issue
  src/common/keybase/keybase.service.ts
  src/endpoints/mex/mex.token.service.ts
Labels: bugfix

#814 remove query pagination from rounds count endpoint
  src/endpoints/rounds/round.controller.ts
Labels: refactoring

#817 Do not filter nodes when sorting
  src/endpoints/nodes/node.service.ts
Labels: bugfix

#816 proxy delegation api endpoints
  config/config.devnet.yaml
  config/config.mainnet.yaml
  config/config.testnet.yaml
  src/common/api-config/api.config.service.ts
  src/endpoints/accounts/account.controller.ts
  src/endpoints/stake/entities/delegation.ts
  src/endpoints/stake/stake.service.ts
Labels: feature

#815 Add pagination to waiting-list endpoint
  src/endpoints/waiting-list/waiting.list.controller.ts
  src/endpoints/waiting-list/waiting.list.service.ts
  src/graphql/entities/waiting.list/waiting.list.input.ts
  src/graphql/entities/waiting.list/waiting.list.query.ts
  src/graphql/schema/schema.gql
  src/test/integration/services/waiting.list.e2e-spec.ts
Labels: refactoring

#818 Add providers filter
  src/endpoints/providers/entities/provider.filter.ts
  src/endpoints/providers/provider.controller.ts
  src/endpoints/providers/provider.service.ts
  src/test/integration/services/providers.e2e-spec.ts
Labels: feature, test

#819 function filter in account transactions transfers endpoint
  src/endpoints/accounts/account.controller.ts
  src/test/integration/services/transactions.e2e-spec.ts
Labels: feature, test

#820 add cache info methods for api services
  src/endpoints/accounts/account.service.ts
  src/endpoints/blocks/block.service.ts
  src/endpoints/delegation/delegation.service.ts
  src/endpoints/network/network.service.ts
  src/endpoints/nfts/nft.service.ts
  src/endpoints/nfttags/tag.service.ts
  src/endpoints/nodes/node.service.ts
  src/endpoints/providers/provider.service.ts
  src/endpoints/stake/stake.service.ts
  src/endpoints/waiting-list/waiting.list.service.ts
  src/test/integration/controllers/nfts.controller.e2e-spec.ts
  src/utils/cache.info.ts
Labels: refactoring

#821 Randomized & resilient keybase.pub fetching
  package-lock.json
  package.json
  src/common/keybase/keybase.service.ts
Labels: bugfix

#823 MultiESDTNFTTransfer marshalized NFT handler
  src/endpoints/transactions/transaction-action/transaction.action.service.ts
Labels: feature

#824 Add scresults unit test (MultiESDTNFTTransfer)
  src/test/integration/services/scresults.e2e-spec.ts
Labels: test

#828 Swaggerdoc for account delegation
  config/config.e2e-mocked.mainnet.yaml
  config/config.e2e.mainnet.yaml
  src/endpoints/accounts/account.controller.ts
  src/endpoints/delegation/delegation.service.ts
  src/endpoints/stake/entities/account.delegation.ts
  src/endpoints/stake/entities/account.undelegation.ts
  src/endpoints/stake/entities/delegation.ts
  src/endpoints/stake/stake.service.ts
  src/test/integration/services/delegation.e2e-spec.ts
Labels: test, refactoring

#827 add try/catch block to handle gateway "account was not found at block"
  src/endpoints/esdt/esdt.address.service.ts
Labels: bugfix
