Repository multiversx/mx-api-service, pull requests merged in 2022-08, with the labels that each got.

#750 add nft collection/tokens validation identifier
  src/endpoints/nfts/nft.controller.ts
  src/endpoints/tokens/token.controller.ts
Labels: refactoring

#752 Host GraphQL on the same port as API
  src/graphql/graphql.module.ts
  src/main.ts
  src/public.app.module.ts
Labels: feature

#710 Extract ElasticSearch functionality into an interface
  config/config.devnet.yaml
  config/config.mainnet.yaml
  config/config.testnet.yaml
  src/common/indexer/elastic/elastic.indexer.module.ts
  src/common/indexer/elastic/elastic.indexer.service.ts
  src/common/indexer/entities/account.history.ts
  src/common/indexer/entities/account.token.history.ts
  src/common/indexer/entities/account.ts
  src/common/indexer/entities/block.ts
  src/common/indexer/entities/collection.ts
  src/common/indexer/entities/index.ts
  src/common/indexer/entities/miniblock.ts
  src/common/indexer/entities/operation.ts
  src/common/indexer/entities/round.ts
  src/common/indexer/entities/sc.deploy.ts
  src/common/indexer/entities/sc.result.ts
  src/common/indexer/entities/tag.ts
  src/common/indexer/entities/token.account.ts
  src/common/indexer/entities/token.ts
  src/common/indexer/entities/transaction.log.ts
  src/common/indexer/entities/transaction.receipt.ts
  src/common/indexer/entities/transaction.ts
  src/common/indexer/indexer.interface.ts
  src/common/indexer/indexer.module.ts
  src/common/indexer/indexer.service.ts
  src/common/indexer/postgres/postgres.indexer.module.ts
  src/common/indexer/postgres/postgres.indexer.service.ts
  src/common/metrics/api.metrics.service.ts
  src/common/protocol/protocol.module.ts
  src/common/protocol/protocol.service.ts
  src/common/rabbitmq/rabbitmq.nft.handler.service.ts
  src/crons/elastic.updater/elastic.updater.service.ts
  src/endpoints/accounts/account.controller.ts
  src/endpoints/accounts/account.service.ts
  src/endpoints/blocks/block.service.ts
  src/endpoints/bls/bls.module.ts
  src/endpoints/bls/bls.service.ts
  src/endpoints/collections/collection.service.ts
  src/endpoints/esdt/esdt.address.service.ts
  src/endpoints/esdt/esdt.service.ts
  src/endpoints/miniblocks/mini.block.service.ts
  src/endpoints/nfts/nft.service.ts
  src/endpoints/nfttags/tag.service.ts
  src/endpoints/rounds/round.service.ts
  src/endpoints/sc-results/scresult.service.ts
  src/endpoints/tokens/token.service.ts
  src/endpoints/transactions/transaction.get.service.ts
  src/endpoints/transactions/transaction.service.ts
  src/endpoints/transfers/transfer.service.ts
  src/test/integration/collections.e2e-spec.ts
Labels: refactoring

#751 collection accounts endpoint
  src/endpoints/collections/collection.controller.ts
  src/endpoints/collections/entities/collection.account.ts
  src/endpoints/nfts/nft.service.ts
Labels: feature

#755 Receiver assets in transaction action receiver
  src/endpoints/transactions/transaction.service.ts
Labels: feature

#756 Sort nodes by locked stake
  src/endpoints/nodes/entities/node.sort.ts
  src/endpoints/nodes/node.service.ts
Labels: feature

#758 Proactively refresh nft media & metadata after processing
  package-lock.json
  package.json
  src/queue.worker/nft.worker/nft.worker.module.ts
  src/queue.worker/nft.worker/queue/job-services/media/nft.media.module.ts
  src/queue.worker/nft.worker/queue/job-services/media/nft.media.service.ts
  src/queue.worker/nft.worker/queue/job-services/metadata/nft.metadata.module.ts
  src/queue.worker/nft.worker/queue/job-services/metadata/nft.metadata.service.ts
Labels: feature

#762 Improve node sort predictability
  src/endpoints/nodes/node.service.ts
Labels: feature

#763 Revert existing GraphQL port
  src/graphql/graphql.module.ts
  src/main.ts
  src/public.app.module.ts
Labels: feature, ignore-for-release

#764 Update NFT metadata on refresh
  src/queue.worker/nft.worker/queue/job-services/metadata/nft.metadata.service.ts
  src/queue.worker/nft.worker/queue/nft.queue.controller.ts
Labels: refactoring

#767 Nft media needs processing
  src/queue.worker/nft.worker/nft.worker.module.ts
  src/queue.worker/nft.worker/nft.worker.service.ts
Labels: bugfix

#754 Flat NFT & collections with nested queries
  package-lock.json
  package.json
  src/endpoints/accounts/account.service.ts
  src/endpoints/accounts/entities/account.detailed.ts
  src/endpoints/collections/entities/nft.collection.account.ts
  src/endpoints/collections/entities/nft.collection.ts
  src/endpoints/esdt/entities/esdt.data.source.ts
  src/endpoints/nfts/entities/nft.account.ts
  src/endpoints/nfts/entities/nft.ts
  src/endpoints/transactions/transaction-action/recognizers/esdt/transaction.action.esdt.nft.recognizer.service.ts
  src/endpoints/transactions/transaction-action/transaction.action.service.ts
  src/endpoints/transactions/transaction.service.ts
  src/endpoints/transactions/transaction.utils.ts
  src/graphql/entities/account.detailed/account.detailed.input.ts
  src/graphql/entities/account.detailed/account.detailed.module.ts
  src/graphql/entities/account.detailed/account.detailed.object.ts
  src/graphql/entities/account.detailed/account.detailed.resolver.ts
  src/graphql/entities/nft.collection/nft.collection.loader.ts
  src/graphql/entities/nft.collection/nft.collection.module.ts
  src/graphql/entities/nft.collection/nft.collection.resolver.ts
  src/graphql/entities/nft/nft.loader.ts
  src/graphql/entities/nft/nft.module.ts
  src/graphql/entities/nft/nft.resolver.ts
  src/graphql/entities/transaction.detailed/transaction.detailed.loader.ts
  src/graphql/entities/transaction.detailed/transaction.detailed.resolver.ts
  src/graphql/schema/schema.gql
  src/public.app.module.ts
  src/test/integration/accounts.e2e-spec.ts
  src/test/integration/blocks.e2e-spec.ts
  src/test/integration/collections.e2e-spec.ts
  src/test/integration/delegation.e2e-spec.ts
  src/test/integration/delegation.legacy.e2e-spec.ts
  src/test/integration/e2e-init.ts
  src/test/integration/esdt.address.e2e-spec.ts
  src/test/integration/esdt.e2e-spec.ts
  src/test/integration/identities.e2e-spec.ts
  src/test/integration/keybase.e2e-spec.ts
  src/test/integration/network.e2e-spec.ts
  src/test/integration/nft.e2e-spec.ts
  src/test/integration/nft.media.e2e-spec.ts
  src/test/integration/nft.metadata.e2e-spec.ts
  src/test/integration/nft.tag.e2e-spec.ts
  src/test/integration/nodes.e2e-spec.ts
  src/test/integration/providers.e2e-spec.ts
  src/test/integration/rounds.e2e-spec.ts
  src/test/integration/scresults.e2e-spec.ts
  src/test/integration/shards.e2e-spec.ts
  src/test/integration/stakes.e2e-spec.ts
  src/test/integration/tokens.e2e-spec.ts
  src/test/integration/transactions.e2e-spec.ts
  src/test/integration/waiting.list.e2e-spec.ts
  src/test/unit/utils/array.extensions.spec.ts
  src/test/unit/utils/string.extensions.spec.ts
  src/test/unit/utils/transaction.utils.spec.ts
  src/utils/token.helpers.ts
Labels: feature

#761 Update packages
  package-lock.json
  package.json
Labels: feature

#768 remove api utils unit tests
  src/test/unit/utils/address.utils.spec.ts
  src/test/unit/utils/batch.utils.spec.ts
  src/test/unit/utils/binary.utils.spec.ts
  src/test/unit/utils/const.utils.spec.ts
  src/test/unit/utils/elastic.query.spec.ts
  src/test/unit/utils/match.utils.spec.ts
  src/test/unit/utils/round.utils.spec.ts
  src/test/unit/utils/tokens.utils.spec.ts
Labels: test, refactoring

#771 Transaction send return actual errors
  src/endpoints/transactions/transaction.service.ts
Labels: bugfix

#770 add withScamInfo query flag
  package-lock.json
  package.json
  src/common/plugins/plugin.service.ts
  src/endpoints/accounts/account.controller.ts
  src/endpoints/collections/collection.controller.ts
  src/endpoints/network/entities/about.ts
  src/endpoints/nfts/entities/nft.query.options.ts
  src/endpoints/nfts/nft.controller.ts
  src/endpoints/nfts/nft.service.ts
  src/endpoints/transactions/transaction.service.ts
  src/test/integration/controllers/nfts.controller.e2e-spec.ts
  src/test/integration/services/nft.e2e-spec.ts
Labels: performance

#766 Transactions endpoint with multiple receivers
  config/config.e2e-mocked.mainnet.yaml
  config/config.e2e.mainnet.yaml
  package-lock.json
  package.json
  src/common/indexer/elastic/elastic.indexer.service.ts
  src/endpoints/accounts/account.controller.ts
  src/endpoints/blocks/block.controller.ts
  src/endpoints/collections/collection.controller.ts
  src/endpoints/esdt/esdt.service.ts
  src/endpoints/mex/mex.controller.ts
  src/endpoints/nfts/nft.controller.ts
  src/endpoints/nfttags/tag.controller.ts
  src/endpoints/nodes/node.controller.ts
  src/endpoints/rounds/round.controller.ts
  src/endpoints/sc-results/scresult.controller.ts
  src/endpoints/shards/shard.controller.ts
  src/endpoints/tokens/token.controller.ts
  src/endpoints/transactions/entities/transaction.filter.ts
  src/endpoints/transactions/transaction.controller.ts
  src/endpoints/transactions/transaction.utils.ts
  src/endpoints/transfers/transfer.controller.ts
  src/graphql/entities/transaction.detailed/transaction.detailed.query.ts
  src/graphql/entities/transaction/transaction.input.ts
  src/test/integration/services/collections.e2e-spec.ts
  src/test/integration/services/tokens.e2e-spec.ts
  src/test/integration/services/transactions.e2e-spec.ts
  src/test/integration/services/transfers.e2e-spec.ts
Labels: feature

#785 withScamInfo support for transactions
  src/common/plugins/plugin.service.ts
  src/endpoints/accounts/account.controller.ts
  src/endpoints/nfts/entities/nft.query.options.ts
  src/endpoints/tokens/token.controller.ts
  src/endpoints/transactions/entities/transactions.query.options.ts
  src/endpoints/transactions/transaction.controller.ts
  src/endpoints/transactions/transaction.service.ts
  src/endpoints/transfers/transfer.service.ts
  src/test/integration/controllers/nfts.controller.e2e-spec.ts
Labels: feature

#780 GraphQL api integration tests
  src/test/integration/controllers/nfts.controller.e2e-spec.ts
  src/test/integration/controllers/tokens.controller.e2e-spec.ts
Labels: test, refactoring

#787 Jailed node status fix
  src/endpoints/nodes/node.service.ts
  src/test/integration/controllers/nodes.controller.e2e-spec.ts
Labels: bugfix

#789 Performance improvements
  package-lock.json
  package.json
  src/common/plugins/plugin.service.ts
  src/crons/elastic.updater/elastic.updater.service.ts
  src/endpoints/collections/collection.service.ts
  src/endpoints/esdt/esdt.service.ts
  src/endpoints/nfts/nft.service.ts
  src/endpoints/tokens/token.transfer.service.ts
  src/endpoints/transactions/transaction.service.ts
  src/endpoints/transfers/transfer.service.ts
  src/interceptors/request.cpu.time.interceptor.ts
  src/interceptors/transaction.logging.interceptor.ts
  src/main.ts
  src/test/integration/controllers/blocks.controller.e2e-spec.ts
  src/test/integration/controllers/miniblocks.controller.e2e-spec.ts
  src/test/integration/controllers/results.controller.e2e-spec.ts
  src/test/integration/services/nft.e2e-spec.ts
  src/test/integration/services/nft.media.e2e-spec.ts
  src/utils/cache.info.ts
Labels: feature

#792 UserToken on github service
  package-lock.json
  package.json
  src/common/github/github.service.ts
  src/test/integration/api/collections.api-spec.ts
Labels: feature

#796 Updated data loader mapping
  package-lock.json
  package.json
  src/endpoints/transactions/transaction.service.ts
  src/graphql/entities/nft.collection/nft.collection.loader.ts
  src/graphql/entities/nft/nft.loader.ts
  src/graphql/entities/smart.contract.result/smart.contract.result.loader.ts
  src/graphql/entities/transaction.detailed/transaction.detailed.loader.ts
  src/graphql/entities/transaction.detailed/transaction.detailed.query.ts
Labels: feature

#794 implement GraphQL endpoints
  src/endpoints/dapp-config/entities/dapp-config.ts
  src/endpoints/usernames/entities/account.username.ts
  src/endpoints/waiting-list/entities/waiting.list.ts
  src/graphql/entities/dapp.config/dap.config.resolver.ts
  src/graphql/entities/dapp.config/dapp.config.module.ts
  src/graphql/entities/dapp.config/dapp.config.query.ts
  src/graphql/entities/username/username.input.ts
  src/graphql/entities/username/username.module.ts
  src/graphql/entities/username/username.query.ts
  src/graphql/entities/username/username.resolver.ts
  src/graphql/entities/waiting.list/waiting.list.module.ts
  src/graphql/entities/waiting.list/waiting.list.query.ts
  src/graphql/entities/waiting.list/waiting.list.resolver.ts
  src/graphql/graphql.module.ts
  src/graphql/schema/schema.gql
  src/test/integration/graphql/dapp.config.graph-spec.ts
  src/test/integration/graphql/username.graph-spec.ts
Labels: feature, test

#798 Added GraphQL transactions unit tests
  src/test/integration/controllers/nfts.controller.e2e-spec.ts
  src/test/integration/graphql/nfts.graph-spec.ts
  src/test/integration/services/metrics.e2e-spec.ts
  src/test/integration/services/nft.e2e-spec.ts
  src/test/integration/services/nodes.e2e-spec.ts
  src/test/unit/graphql/entities/transaction.detailed/transaction.deatiled.query.spec.ts
  src/test/unit/graphql/entities/transaction/transaction.query.spec.ts
  src/test/unit/graphql/mocks/transaction.service.mock.ts
Labels: test
