Repository multiversx/mx-api-service, pull requests merged in 2022-07, with the labels that each got.

#702 Dependabot alert
  package-lock.json
  package.json
Labels: enhancement

#725 Adjust rarity field names
  src/endpoints/nfts/nft.service.ts
Labels: feature, ignore-for-release

#726 Token economics improvements
  package-lock.json
  package.json
  src/endpoints/esdt/esdt.service.ts
  src/endpoints/mex/mex.token.service.ts
  src/endpoints/network/entities/economics.ts
  src/endpoints/network/network.module.ts
  src/endpoints/network/network.service.ts
  src/endpoints/nfts/nft.service.ts
  src/endpoints/tokens/entities/token.ts
  src/endpoints/tokens/token.controller.ts
  src/test/unit/utils/array.extensions.spec.ts
  src/utils/cache.info.ts
Labels: feature

#727 Add unlock schedule to mex token
  config/config.devnet.yaml
  package-lock.json
  package.json
  src/common/entities/unlock-schedule.ts
  src/common/locked-asset/locked-asset.module.ts
  src/common/locked-asset/locked-asset.service.ts
  src/endpoints/nfts/entities/nft.ts
  src/endpoints/nfts/nft.module.ts
  src/endpoints/nfts/nft.service.ts
  src/utils/cache.info.ts
  src/utils/token.utils.ts
Labels: feature

#734 Restore transaction logging
  src/interceptors/transaction.logging.interceptor.ts
  src/main.ts
Labels: bug

#737 Update PULL_REQUEST_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#735 Account assets for transaction
  src/common/assets/assets.service.ts
  src/common/assets/entities/account.assets.ts
  src/crons/cache.warmer/cache.warmer.service.ts
  src/endpoints/sc-results/entities/smart.contract.result.ts
  src/endpoints/sc-results/scresult.controller.ts
  src/endpoints/sc-results/scresult.module.ts
  src/endpoints/sc-results/scresult.service.ts
  src/endpoints/tokens/token.transfer.service.ts
  src/endpoints/transactions/entities/transaction.log.event.ts
  src/endpoints/transactions/entities/transaction.log.ts
  src/endpoints/transactions/entities/transaction.operation.ts
  src/endpoints/transactions/entities/transaction.ts
  src/endpoints/transactions/transaction.module.ts
  src/endpoints/transactions/transaction.service.ts
  src/endpoints/transfers/transfer.module.ts
  src/endpoints/transfers/transfer.service.ts
  src/test/unit/utils/transaction.utils.spec.ts
Labels: feature

#736 Account nft validation
  src/endpoints/collections/collection.service.ts
  src/endpoints/nfts/nft.service.ts
  src/endpoints/tokens/token.service.ts
  src/test/data/transactions/transactions.with.logs.ts
  src/test/integration/controllers/accounts.controller.e2e-spec.ts
  src/test/integration/controllers/blocks.controller.e2e-spec.ts
  src/test/integration/controllers/collections.controller.e2e-spec.ts
  src/test/integration/controllers/dappconfig.controller.e2e-spec.ts
  src/test/integration/controllers/delegation.controller.e2e-spec.ts
  src/test/integration/controllers/health.check.controller.e2e-spec.ts
  src/test/integration/controllers/identities.controller.e2e-spec.ts
  src/test/integration/controllers/miniblocks.controller.e2e-spec.ts
  src/test/integration/controllers/nfts.controller.e2e-spec.ts
  src/test/integration/controllers/nodes.controller.e2e-spec.ts
  src/test/integration/controllers/providers.controller.e2e-spec.ts
  src/test/integration/controllers/rounds.controller.e2e-spec.ts
  src/test/integration/controllers/sc-results.controller.e2e-spec.ts
  src/test/integration/controllers/shards.controller.e2e-spec.ts
  src/test/integration/controllers/stake.controller.e2e-spec.ts
  src/test/integration/controllers/tags.controller.e2e-spec.ts
  src/test/integration/controllers/tokens.controller.e2e-spec.ts
  src/test/integration/controllers/transactions.controller.e2e-spec.ts
  src/test/integration/controllers/username.controller.e2e-spec.ts
  src/test/integration/controllers/waiting-list.controller.e2e-spec.ts
  src/utils/token.utils.ts
Labels: bugfix, test

#741 Update dependencies
  .github/PULL_REQUEST_TEMPLATE.md
  package-lock.json
  package.json
Labels: ignore-for-release

#744 Label for DNS contracts
  src/common/assets/assets.service.ts
  src/utils/dns.contracts.ts
Labels: feature

#745 Integrate Token Validator pipes from erdnest
  package-lock.json
  package.json
  src/common/locked-asset/locked-asset.service.ts
  src/endpoints/accounts/account.controller.ts
  src/endpoints/collections/collection.controller.ts
  src/endpoints/collections/collection.service.ts
  src/endpoints/esdt/esdt.address.service.ts
  src/endpoints/esdt/esdt.service.ts
  src/endpoints/nfts/nft.controller.ts
  src/endpoints/nfts/nft.extendedattributes.service.ts
  src/endpoints/nfts/nft.service.ts
  src/endpoints/tokens/token.controller.ts
  src/endpoints/tokens/token.service.ts
  src/queue.worker/nft.worker/queue/job-services/assets/nft.asset.service.ts
  src/queue.worker/nft.worker/queue/job-services/media/nft.media.service.ts
  src/queue.worker/nft.worker/queue/job-services/thumbnails/nft.thumbnail.service.ts
  src/test/unit/utils/token.utils.spec.ts
  src/test/unit/utils/tokens.utils.spec.ts
  src/utils/token.helpers.ts
Labels: refactoring
