Repository multiversx/mx-api-service, pull requests merged in 2023-01, with the labels that each got.

#928 rebrand api labels to multiversx
  .github/CODE_OF_CONDUCT.md
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/release.yml
  README.md
  config/config.devnet.yaml
  config/config.e2e-mocked.mainnet.yaml
  config/config.e2e.mainnet.yaml
  config/config.mainnet.yaml
  config/config.testnet.yaml
  config/dapp.config.devnet.json
  config/dapp.config.mainnet.json
  config/dapp.config.testnet.json
  src/assets/img/mvx-ledger-icon-mint.png
  src/common/assets/assets.service.ts
  src/endpoints/dapp-config/entities/dapp-config.ts
  src/endpoints/mex/mex.controller.ts
  src/graphql/entities/maiar.exchange/mex.economics/mex.economics.query.ts
  src/graphql/entities/maiar.exchange/mex.farms/mex.farms.query.ts
  src/graphql/entities/maiar.exchange/mex.pairs/mex.pairs.query.ts
  src/graphql/entities/maiar.exchange/mex.token/mex.token.query.ts
  src/graphql/schema/schema.gql
  src/main.ts
  src/test/integration/controllers/maiar.exchange.controller.e2e-spec.ts
  src/test/integration/controllers/proxy.controller.e2e-spec.ts
  src/test/integration/controllers/tokens.controller.e2e-spec.ts
  src/test/integration/graphql/maiar.exchange.graph-spec.ts
  src/test/integration/graphql/tokens.graph-spec.ts
  src/test/integration/services/api.config.e2e-spec.ts
  src/test/integration/services/dapp.config.e2e-spec.ts
  src/test/integration/services/providers.e2e-spec.ts
  src/test/integration/services/tokens.e2e-spec.ts
Labels: refactoring, hotfix

#926 add unlock epoch for xmex
  package-lock.json
  package.json
  src/common/locked-asset/entities/locked.tokens.interface.ts
  src/common/locked-asset/entities/unlock.milestone.model.ts
  src/common/locked-asset/locked-asset.service.ts
  src/endpoints/nfts/entities/nft.ts
  src/endpoints/nfts/nft.service.ts
  src/graphql/schema/schema.gql
  src/test/integration/graphql/nfts.graph-spec.ts
  src/test/integration/services/nft.e2e-spec.ts
  src/utils/cache.info.ts
Labels: feature

#848 api status checker
  config/config.devnet.yaml
  config/config.mainnet.yaml
  config/config.testnet.yaml
  src/common/api-config/api.config.service.ts
  src/common/metrics/status.metrics.module.ts
  src/common/metrics/status.metrics.service.ts
  src/crons/status.checker/status.checker.module.ts
  src/crons/status.checker/status.checker.service.ts
  src/endpoints/mex/mex.controller.ts
  src/endpoints/mex/mex.farm.service.ts
  src/endpoints/mex/mex.pair.service.ts
  src/endpoints/mex/mex.token.service.ts
  src/main.ts
Labels: feature

#866 update graphql service
  src/endpoints/accounts/entities/account.esdt.history.ts
  src/endpoints/accounts/entities/account.history.ts
  src/endpoints/accounts/entities/account.key.ts
  src/endpoints/accounts/entities/deployed.contract.ts
  src/endpoints/delegation.legacy/entities/account.delegation.legacy.ts
  src/endpoints/stake/entities/account.delegation.ts
  src/endpoints/stake/entities/account.undelegation.ts
  src/endpoints/stake/entities/provider.stake.ts
  src/endpoints/stake/entities/provider.unstaked.tokens.ts
  src/endpoints/tokens/entities/token.with.balance.ts
  src/graphql/entities/account.detailed/account.detailed.input.ts
  src/graphql/entities/account.detailed/account.detailed.module.ts
  src/graphql/entities/account.detailed/account.detailed.object.ts
  src/graphql/entities/account.detailed/account.detailed.resolver.ts
  src/graphql/schema/schema.gql
  src/test/integration/graphql/accounts.graph-spec.ts
  src/test/unit/graphql/entities/account.detailed/account.detailed.resolver.spec.ts
Labels: feature, test, refactoring

#934 Auth setting allow native auth tokens
  package-lock.json
  src/main.ts
  src/utils/jwt.or.native.auth.guard.ts
Labels: feature

#874 Hot swappable settings
  docker-compose.yml
  src/common/indexer/elastic/elastic.indexer.service.ts
  src/common/persistence/mongodb/entities/hot.swappable.setting.ts
  src/common/persistence/mongodb/mongo.db.module.ts
  src/common/persistence/mongodb/mongo.db.service.ts
  src/common/persistence/passthrough/pass.through.service.ts
  src/common/persistence/persistence.interface.ts
  src/common/persistence/persistence.service.ts
  src/common/settings/settings.module.ts
  src/common/settings/settings.service.ts
  src/crons/cache.warmer/cache.warmer.service.ts
  src/endpoints/vm.query/vm.query.module.ts
  src/endpoints/vm.query/vm.query.service.ts
  src/graphql/entities/transfers/transfers.query.ts
  src/graphql/entities/transfers/transfers.resolver.ts
  src/main.ts
  src/utils/cache.info.ts
Labels: feature

#937 Allow herotags for smart contracts as well
  src/endpoints/accounts/account.service.ts
Labels: feature

#877 type safe interactions with gateway
  src/common/gateway/entities/account.detailed.ts
  src/common/gateway/entities/account.ts
  src/common/gateway/entities/esdt.roles.ts
  src/common/gateway/entities/esdt.supply.ts
  src/common/gateway/entities/heartbeats.status.ts
  src/common/gateway/entities/network.config.ts
  src/common/gateway/entities/network.economics.ts
  src/common/gateway/entities/network.status.ts
  src/common/gateway/entities/nft.data.ts
  src/common/gateway/entities/smart.contract.results.detailed.ts
  src/common/gateway/entities/token.data.ts
  src/common/gateway/entities/transaction.ts
  src/common/gateway/gateway.service.ts
  src/common/locked-asset/locked-asset.service.ts
  src/common/metrics/api.metrics.service.ts
  src/common/protocol/protocol.service.ts
  src/crons/cache.warmer/cache.warmer.service.ts
  src/endpoints/accounts/account.service.ts
  src/endpoints/esdt/esdt.address.service.ts
  src/endpoints/esdt/esdt.service.ts
  src/endpoints/network/network.service.ts
  src/endpoints/nodes/node.service.ts
  src/endpoints/stake/stake.service.ts
  src/endpoints/tokens/token.service.ts
  src/endpoints/transactions/transaction.get.service.ts
  src/test/integration/services/network.e2e-spec.ts
Labels: refactoring

#938 Fix XMEX / LKMEX decoding error
  src/common/locked-asset/locked-asset.service.ts
Labels: bugfix

#941 Refresh token & account assets every 10 minutes
  src/crons/cache.warmer/cache.warmer.service.ts
Labels: feature

#890 Show transaction prices
  package-lock.json
  package.json
  src/common/api-config/api.config.service.ts
  src/common/external/data.api.module.ts
  src/common/external/data.api.service.ts
  src/common/external/entities/data.quote.type.ts
  src/common/plugins/plugin.service.ts
  src/crons/cache.warmer/cache.warmer.module.ts
  src/crons/cache.warmer/cache.warmer.service.ts
  src/crons/status.checker/status.checker.service.ts
  src/endpoints/network/network.service.ts
  src/endpoints/transactions/entities/transaction.operation.ts
  src/endpoints/transactions/transaction.module.ts
  src/endpoints/transactions/transaction.price.service.ts
  src/endpoints/transactions/transaction.service.ts
  src/endpoints/transfers/transfer.service.ts
  src/graphql/schema/schema.gql
  src/test/integration/services/api.config.e2e-spec.ts
  src/test/integration/services/transfers.e2e-spec.ts
  src/utils/cache.info.ts
Labels: feature

#895 add codecov specific version
  .github/workflows/integration.graph.test.yml
  .github/workflows/integration.tests.yml
  .github/workflows/lint.yml
  .github/workflows/unit.tests.yml
Labels: refactoring

#896 explorer statistics next steps
  src/endpoints/network/entities/stats.ts
  src/endpoints/network/network.module.ts
  src/endpoints/network/network.service.ts
  src/graphql/schema/schema.gql
Labels: feature

#899 Use Lock decorator
  package-lock.json
  package.json
  src/common/api-config/api.config.service.ts
  src/crons/cache.warmer/cache.warmer.service.ts
  src/crons/elastic.updater/elastic.updater.service.ts
  src/crons/nft/nft.cron.service.ts
  src/endpoints/mex/mex.pair.service.ts
Labels: feature

#945 Add verification endpoint and isVerified attribute for smart contracts
  config/config.devnet.yaml
  config/config.e2e-mocked.mainnet.yaml
  config/config.e2e.mainnet.yaml
  config/config.mainnet.yaml
  config/config.testnet.yaml
  src/common/api-config/api.config.service.ts
  src/endpoints/accounts/account.controller.ts
  src/endpoints/accounts/account.service.ts
  src/endpoints/accounts/entities/account.detailed.ts
  src/endpoints/accounts/entities/account.verification.source.ts
  src/endpoints/accounts/entities/account.verification.status.ts
  src/endpoints/accounts/entities/account.verification.ts
  src/test/integration/services/api.config.e2e-spec.ts
  src/test/integration/services/nft.thumbnail.e2e-spec.ts
Labels: feature, test

#929 Add support for multiPairSwap in transaction action
  src/endpoints/mex/entities/mex.settings.ts
  src/endpoints/mex/mex.settings.service.ts
  src/endpoints/transactions/transaction-action/recognizers/mex/entities/mex.function.options.ts
  src/endpoints/transactions/transaction-action/recognizers/mex/mex.pair.action.recognizer.service.ts
  src/test/integration/services/transactions.e2e-spec.ts
Labels: feature

#948 add nft name instead of collection name in transaction operation
  src/endpoints/tokens/token.transfer.service.ts
  src/graphql/schema/schema.gql
Labels: feature
