Repository multiversx/mx-api-service, pull requests merged in 2023-03, with the labels that each got.

#990 Remove unnecessary logs
  src/endpoints/proxy/proxy.controller.ts
Labels: feature

#988 add before and after query params for accounts history
  src/common/indexer/elastic/elastic.indexer.helper.ts
  src/common/indexer/elastic/elastic.indexer.service.ts
  src/common/indexer/indexer.interface.ts
  src/common/indexer/indexer.service.ts
  src/endpoints/accounts/account.controller.ts
  src/endpoints/accounts/account.service.ts
  src/endpoints/accounts/entities/account.history.filter.ts
  src/graphql/entities/account.detailed/account.detailed.input.ts
  src/graphql/entities/account.detailed/account.detailed.resolver.ts
  src/graphql/schema/schema.gql
  src/test/integration/services/accounts.e2e-spec.ts
  src/test/integration/services/tokens.e2e-spec.ts
Labels: feature

#989 add scheduledRootHash block field
  src/endpoints/blocks/block.service.ts
  src/endpoints/blocks/entities/block.ts
  src/graphql/schema/schema.gql
  src/test/integration/services/blocks.e2e-spec.ts
Labels: feature, test

#991 support for multiple miniblocks hashes
  src/common/indexer/elastic/elastic.indexer.helper.ts
  src/common/indexer/elastic/elastic.indexer.service.ts
  src/common/indexer/entities/miniblock.ts
  src/common/indexer/indexer.interface.ts
  src/common/indexer/indexer.service.ts
  src/common/indexer/postgres/entities/miniblock.db.ts
  src/common/indexer/postgres/postgres.indexer.service.ts
  src/endpoints/accounts/account.controller.ts
  src/endpoints/blocks/block.controller.ts
  src/endpoints/blocks/block.service.ts
  src/endpoints/blocks/entities/block.filter.ts
  src/endpoints/miniblocks/entities/mini.block.filter.ts
  src/endpoints/miniblocks/mini.block.controller.ts
  src/endpoints/miniblocks/mini.block.service.ts
  src/endpoints/tokens/token.controller.ts
  src/endpoints/transactions/entities/transaction.detailed.ts
  src/endpoints/transactions/entities/transactions.query.options.ts
  src/endpoints/transfers/transfer.controller.ts
  src/endpoints/transfers/transfer.service.ts
  src/graphql/schema/schema.gql
  src/test/integration/services/blocks.e2e-spec.ts
Labels: feature

#992 Provide token collection in account tokens endpoints if MetaESDT
  src/endpoints/tokens/entities/token.ts
  src/endpoints/tokens/token.service.ts
  src/graphql/schema/schema.gql
  src/test/integration/services/tokens.e2e-spec.ts
Labels: feature, test

#994 Provide token nonce in account tokens endpoints if meta esdt
  src/endpoints/tokens/entities/token.ts
  src/endpoints/tokens/token.service.ts
  src/graphql/schema/schema.gql
  src/test/integration/services/tokens.e2e-spec.ts
Labels: feature

#993 Count token accounts in chunks
  src/crons/cache.warmer/cache.warmer.service.ts
  src/endpoints/esdt/esdt.service.ts
Labels: bugfix

#996 add block info fields when withBlockInfo = false
  package-lock.json
  package.json
  src/common/protocol/protocol.service.ts
  src/endpoints/accounts/account.controller.ts
  src/endpoints/accounts/account.service.ts
  src/endpoints/nfts/nft.service.ts
  src/endpoints/tokens/token.controller.ts
  src/endpoints/transactions/transaction.controller.ts
  src/endpoints/transactions/transaction.get.service.ts
  src/endpoints/transactions/transaction.service.ts
  src/endpoints/transfers/transfer.controller.ts
  src/endpoints/transfers/transfer.service.ts
  src/utils/cache.info.ts
Labels: feature

#998 Updated sdk nestjs to latest version
  package-lock.json
  package.json
Labels: ignore-for-release

#1000 Update sdk nestjs to latest version
  package-lock.json
  package.json
Labels: ignore-for-release

#1010 Search by proper field in accountsesdthistory index
  src/common/indexer/elastic/elastic.indexer.helper.ts
Labels: bugfix

#1011 add account token history count
  src/common/indexer/elastic/elastic.indexer.service.ts
  src/common/indexer/indexer.interface.ts
  src/common/indexer/indexer.service.ts
  src/common/indexer/postgres/postgres.indexer.service.ts
  src/endpoints/accounts/account.controller.ts
  src/endpoints/accounts/account.service.ts
Labels: feature

#1020 Native auth guards only
  src/endpoints/caching/local.cache.controller.ts
  src/endpoints/caching/remote.cache.controller.ts
  src/endpoints/process-nfts/process.nfts.public.controller.ts
  src/endpoints/transactions.batch/transactions.batch.controller.ts
Labels: feature
