Repository multiversx/mx-api-service, pull requests merged in 2023-09, with the labels that each got.

#1084 add support for notStaked nodes and add support for multiple keys filter
  src/endpoints/accounts/account.service.ts
  src/endpoints/nodes/entities/node.filter.ts
  src/endpoints/nodes/entities/node.status.ts
  src/endpoints/nodes/node.controller.ts
  src/endpoints/nodes/node.service.ts
  src/endpoints/providers/provider.service.ts
Labels: feature

#1101 add denominated supply
  src/endpoints/mex/mex.token.service.ts
  src/endpoints/tokens/entities/token.detailed.ts
  src/endpoints/tokens/entities/token.supply.options.ts
  src/endpoints/tokens/entities/token.ts
  src/endpoints/tokens/token.controller.ts
  src/endpoints/tokens/token.service.ts
Labels: feature

#1118 add support for guardian info in username controller
  src/endpoints/usernames/username.controller.ts
  src/endpoints/usernames/username.service.ts
  src/graphql/schema/schema.gql
  src/test/integration/controllers/username.controller.e2e-spec.ts
  src/test/integration/services/username.e2e-spec.ts
Labels: feature

#1120 add token timestamp
  src/common/indexer/elastic/elastic.indexer.service.ts
  src/endpoints/esdt/esdt.service.ts
  src/endpoints/tokens/entities/token.properties.ts
  src/test/integration/services/tokens.e2e-spec.ts
Labels: feature

#1125 update API with latest sdk-nestjs version
  package-lock.json
  package.json
  src/endpoints/providers/provider.service.ts
Labels: bugfix, dependencies

#1129 Economics refactoring
  src/endpoints/network/network.service.ts
  src/test/integration/controllers/tokens.controller.e2e-spec.ts
Labels: refactoring
