Repository multiversx/mx-api-service, pull requests merged in 2023-04, with the labels that each got.

#1028 Add support for Guardian Data
  package-lock.json
  package.json
  src/common/gateway/entities/guardian.data.ts
  src/common/gateway/entities/guardian.result.ts
  src/common/gateway/entities/guardian.ts
  src/common/gateway/gateway.service.ts
  src/endpoints/accounts/account.controller.ts
  src/endpoints/accounts/account.service.ts
  src/endpoints/accounts/entities/account.detailed.ts
  src/test/integration/services/accounts.e2e-spec.ts
Labels: feature, test

#1027 support for provider avatar
  src/endpoints/identities/identities.controller.ts
  src/endpoints/identities/identities.service.ts
  src/endpoints/providers/provider.controller.ts
  src/endpoints/providers/provider.module.ts
  src/endpoints/providers/provider.service.ts
  src/test/integration/services/accounts.e2e-spec.ts
Labels: feature

#1032 update unit tests
  src/test/integration/controllers/tokens.controller.e2e-spec.ts
  src/test/integration/services/blocks.e2e-spec.ts
  src/test/integration/services/bls.e2e-spec.ts
  src/test/integration/services/delegation.e2e-spec.ts
  src/test/integration/services/delegation.legacy.e2e-spec.ts
  src/test/integration/services/network.e2e-spec.ts
  src/test/integration/services/nft.tag.e2e-spec.ts
  src/test/integration/services/rounds.e2e-spec.ts
  src/test/integration/services/stake.e2e-spec.ts
  src/test/integration/services/stakes.e2e-spec.ts
  src/test/integration/services/tags.e2e-spec.ts
  src/test/integration/services/tokens.e2e-spec.ts
  src/test/integration/services/transfers.e2e-spec.ts
  src/test/integration/services/username.e2e-spec.ts
  src/test/mocks/tokens.filtered.mock.json
  src/test/mocks/tokens.mock.json
Labels: test

#1034 Updated sdk-nestjs version to 0.5.1
  package-lock.json
  package.json
  src/utils/cache.info.ts
Labels: ignore-for-release

#1036 Case insensitive search for collections
  package-lock.json
  package.json
Labels: bugfix

#1035 update token service tests
  src/test/integration/services/tokens.e2e-spec.ts
  src/test/mocks/token.accounts.mock.json
  src/test/unit/utils/typeorm.spec.ts
Labels: test

#1039 update node service unit tests
  src/graphql/schema/schema.gql
  src/test/integration/api/accounts.api-spec.ts
  src/test/integration/api/blocks.api-spec.ts
  src/test/integration/api/collections.api-spec.ts
  src/test/integration/api/nfts.api-spec.ts
  src/test/integration/api/nodes.api-spec.ts
  src/test/integration/api/providers.api-spec.ts
  src/test/integration/api/results.api-spec.ts
  src/test/integration/api/rounds.api-spec.ts
  src/test/integration/api/shards.api-spec.ts
  src/test/integration/api/tags.api-spec.ts
  src/test/integration/api/tokens.api-spec.ts
  src/test/integration/api/transactions.api-spec.ts
  src/test/integration/services/nodes.e2e-spec.ts
  src/test/mocks/nodes.mock.json
  src/utils/api.checker.ts
Labels: test

#1044 ffmpeg generate waveform from audio file handle error
  .github/workflows/chatgpt.yml
  src/queue.worker/nft.worker/queue/job-services/thumbnails/nft.thumbnail.service.ts
Labels: bugfix

#1047 support for egld token filter in transfers endpoint
  src/common/indexer/elastic/elastic.indexer.helper.ts
Labels: feature

#1048 Owner invalidation in case of makeNewContractFromValidatorData function
  src/crons/transaction.processor/transaction.processor.service.ts
  src/utils/cache.info.ts
Labels: feature

#1050 filter transactions by no function
  package-lock.json
  package.json
  src/common/indexer/elastic/elastic.indexer.helper.ts
  src/endpoints/accounts/account.controller.ts
  src/endpoints/collections/collection.controller.ts
  src/endpoints/tokens/token.controller.ts
  src/endpoints/transactions/transaction.controller.ts
  src/endpoints/transfers/transfer.controller.ts
  src/test/integration/services/transfers.e2e-spec.ts
Labels: feature

#1054 Expose Websocket port only on public api instances
  src/common/pubsub/pub.sub.listener.controller.ts
  src/common/pubsub/pub.sub.listener.module.ts
  src/common/websockets/web-socket-publisher-controller.ts
  src/common/websockets/web-socket-publisher-module.ts
  src/main.ts
Labels: bugfix
