Repository multiversx/mx-api-service, pull requests merged in 2023-06, with the labels that each got.

#1079 add support for remainingUnbondPeriod for account keys
  src/endpoints/accounts/account.module.ts
  src/endpoints/accounts/account.service.ts
  src/endpoints/accounts/entities/account.key.ts
  src/endpoints/nodes/node.service.ts
  src/endpoints/providers/entities/provider.filter.ts
  src/endpoints/providers/provider.controller.ts
  src/endpoints/providers/provider.service.ts
  src/test/integration/services/accounts.e2e-spec.ts
  src/test/integration/services/delegation.e2e-spec.ts
Labels: feature

#1081 Collection name fallback in transaction operation
  src/endpoints/tokens/token.transfer.service.ts
Labels: feature

#1082 Node status leaving fix
  src/endpoints/nodes/node.service.ts
  src/graphql/schema/schema.gql
Labels: bugfix

#1083 Account token identifier fix if smart contract
  src/endpoints/tokens/token.service.ts
Labels: bugfix

#1085 add support for automaticActivation and checkCapOnRedelegate for providers
  src/endpoints/providers/provider.service.ts
  src/test/integration/services/providers.e2e-spec.ts
Labels: feature, test

#1089 Return prices for experimental DEX tokens
  src/endpoints/mex/entities/mex.pair.exchange.ts
  src/endpoints/mex/entities/mex.pair.type.ts
  src/endpoints/mex/mex.pair.service.ts
  src/endpoints/mex/mex.token.service.ts
  src/graphql/schema/schema.gql
Labels: feature
