Repository multiversx/mx-api-service, pull requests merged in 2023-07, with the labels that each got.

#1090 add new test file for transactions batch
  src/test/integration/services/transactions-batch.e2e-spec.ts
Labels: test

#1094 Event topics handle undefined
  src/endpoints/blocks/block.controller.ts
  src/endpoints/tokens/token.transfer.service.ts
  src/test/integration/controllers/nfts.controller.e2e-spec.ts
  src/test/integration/graphql/nfts.graph-spec.ts
  src/test/integration/services/transactions-batch.e2e-spec.ts
Labels: bugfix

#1091 add support for transaction process status
  src/common/gateway/entities/gateway.component.request.ts
  src/common/gateway/entities/transaction.process.status.ts
  src/common/gateway/gateway.service.ts
  src/endpoints/proxy/proxy.controller.ts
  src/endpoints/transactions/entities/transaction.detailed.ts
  src/endpoints/transactions/transaction.controller.ts
  src/endpoints/transactions/transaction.service.ts
  src/test/integration/services/transactions.e2e-spec.ts
Labels: feature, test

#1099 Trim NFT url when hashing
  src/graphql/schema/schema.gql
  src/utils/token.helpers.ts
Labels: bugfix

#1100 include price for Hatom tokens
  src/common/data-api/data-api.service.ts
  src/common/data-api/entities/data-api.token.ts
  src/test/integration/services/data-api.e2e-spec.ts
Labels: feature
