Repository multiversx/mx-api-service, pull requests merged in 2023-02, with the labels that each got.

#912 Invalidate cache on `transferOwnership` event
  config/config.devnet.yaml
  src/common/rabbitmq/entities/notifier.event.identifier.ts
  src/common/rabbitmq/rabbitmq.consumer.ts
  src/common/rabbitmq/rabbitmq.module.ts
  src/common/rabbitmq/rabbitmq.nft.handler.service.ts
  src/common/rabbitmq/rabbitmq.token.handler.service.ts
Labels: bugfix

#950 change default nft rarity algorithm to openRarity
  src/endpoints/nfts/nft.service.ts
Labels: refactoring

#952 add function filter to transfers endpoint
  src/endpoints/transfers/transfer.controller.ts
  src/test/integration/services/transfers.e2e-spec.ts
Labels: bugfix

#953 Stats endpoint real transactions
  src/endpoints/network/network.service.ts
Labels: feature

#915 add deployTxHash attribute
  src/common/indexer/indexer.interface.ts
  src/common/indexer/indexer.service.ts
  src/endpoints/accounts/account.controller.ts
  src/endpoints/accounts/account.service.ts
  src/endpoints/accounts/entities/account.detailed.ts
  src/endpoints/accounts/entities/contract.upgrades.ts
  src/graphql/schema/schema.gql
  src/test/integration/services/tokens.e2e-spec.ts
  src/utils/cache.info.ts
Labels: feature, test

#921 include canAddSpecialRoles attribute in token response body
  src/endpoints/esdt/esdt.service.ts
  src/test/integration/services/tokens.e2e-spec.ts
Labels: feature

#939 add provider missing fields from delegation api
  src/common/assets/assets.service.ts
  src/endpoints/providers/entities/delegation.data.ts
  src/endpoints/providers/entities/provider.ts
  src/endpoints/providers/provider.controller.ts
  src/endpoints/providers/provider.service.ts
  src/graphql/entities/providers/providers.query.ts
  src/graphql/schema/schema.gql
  src/test/integration/services/identities.e2e-spec.ts
  src/test/integration/services/nodes.e2e-spec.ts
  src/test/integration/services/providers.e2e-spec.ts
  src/utils/cache.info.ts
Labels: feature, test

#923 extract all token details from es
  config/config.devnet.yaml
  package-lock.json
  package.json
  src/common/api-config/api.config.service.ts
  src/common/indexer/elastic/elastic.indexer.service.ts
  src/endpoints/esdt/esdt.service.ts
  src/endpoints/tokens/entities/token.properties.ts
  src/endpoints/tokens/token.service.ts
  src/graphql/schema/schema.gql
  src/main.ts
Labels: feature

#962 fix provider extra fields
  src/endpoints/providers/provider.service.ts
Labels: bugfix

#963 Use light gateway for VM queries
  src/common/gateway/gateway.service.ts
Labels: bugfix

#964 add supply to any non fungible esdt
  src/endpoints/tokens/token.service.ts
  src/graphql/schema/schema.gql
  src/test/integration/controllers/tokens.controller.e2e-spec.ts
  src/test/integration/graphql/tokens.graph-spec.ts
  src/test/integration/services/tokens.e2e-spec.ts
Labels: feature

#892 account auctions endpoint
  config/config.devnet.yaml
  config/config.mainnet.yaml
  config/config.testnet.yaml
  src/common/api-config/api.config.service.ts
  src/common/graphql/graphql.service.ts
  src/endpoints/accounts/account.controller.ts
  src/endpoints/collections/collection.controller.ts
  src/endpoints/collections/collection.module.ts
  src/endpoints/collections/collection.service.ts
  src/endpoints/collections/entities/nft.collection.ts
  src/endpoints/endpoints.controllers.module.ts
  src/endpoints/endpoints.services.module.ts
  src/endpoints/marketplace/entities/account.auction.stats.ts
  src/endpoints/marketplace/entities/account.auctions.ts
  src/endpoints/marketplace/entities/auction.status.ts
  src/endpoints/marketplace/entities/auctions.filter.ts
  src/endpoints/marketplace/entities/auctions.ts
  src/endpoints/marketplace/entities/bids.ts
  src/endpoints/marketplace/entities/collection.auction.stats.ts
  src/endpoints/marketplace/entities/collection.stats.filter.ts
  src/endpoints/marketplace/entities/explore.collections.stats.ts
  src/endpoints/marketplace/graphql/account.auctions.query.ts
  src/endpoints/marketplace/graphql/account.stats.query.ts
  src/endpoints/marketplace/graphql/auctions.query.ts
  src/endpoints/marketplace/graphql/collection.stats.query.ts
  src/endpoints/marketplace/graphql/explore.query.ts
  src/endpoints/marketplace/nft.marketplace.controller.ts
  src/endpoints/marketplace/nft.marketplace.module.ts
  src/endpoints/marketplace/nft.marketplace.service.ts
  src/endpoints/mex/mex.controller.ts
  src/endpoints/mex/mex.token.service.ts
  src/endpoints/transactions/transaction-action/recognizers/mex/transaction.action.mex.recognizer.service.ts
  src/graphql/entities/graphql.services.module.ts
  src/graphql/entities/xexchange/mex.economics/mex.economics.query.ts
  src/graphql/entities/xexchange/mex.economics/mex.economics.resolver.ts
  src/graphql/entities/xexchange/mex.farms/mex.farms.input.ts
  src/graphql/entities/xexchange/mex.farms/mex.farms.query.ts
  src/graphql/entities/xexchange/mex.farms/mex.farms.resolver.ts
  src/graphql/entities/xexchange/mex.pairs/mex.pairs.input.ts
  src/graphql/entities/xexchange/mex.pairs/mex.pairs.query.ts
  src/graphql/entities/xexchange/mex.pairs/mex.pairs.resolver.ts
  src/graphql/entities/xexchange/mex.token.module.ts
  src/graphql/entities/xexchange/mex.token/mex.token.input.ts
  src/graphql/entities/xexchange/mex.token/mex.token.query.ts
  src/graphql/entities/xexchange/mex.token/mex.token.resolver.ts
  src/graphql/schema/schema.gql
  src/public.app.module.ts
  src/test/integration/services/api.config.e2e-spec.ts
  src/test/integration/services/tokens.e2e-spec.ts
  src/test/mocks/tokens.mock.json
Labels: feature

#957 Extract all token details from es
  config/config.devnet.yaml
  package-lock.json
  package.json
  src/common/api-config/api.config.service.ts
  src/common/indexer/elastic/elastic.indexer.service.ts
  src/endpoints/esdt/esdt.service.ts
  src/endpoints/tokens/entities/token.properties.ts
  src/endpoints/tokens/token.service.ts
  src/graphql/schema/schema.gql
  src/main.ts
Labels: feature

#966 apply supply also to NFTs and SFTs
  src/endpoints/tokens/token.service.ts
Labels: feature

#971 Feature flag for exchange service
  src/common/api-config/api.config.service.ts
  src/common/locked-asset/locked-asset.module.ts
  src/crons/cache.warmer/cache.warmer.module.ts
  src/crons/cache.warmer/cache.warmer.service.ts
  src/endpoints/endpoints.controllers.module.ts
  src/endpoints/endpoints.services.module.ts
  src/endpoints/esdt/esdt.module.ts
  src/endpoints/mex/mex.farm.service.ts
  src/endpoints/mex/mex.module.ts
  src/endpoints/mex/mex.pair.service.ts
  src/endpoints/mex/mex.settings.service.ts
  src/endpoints/mex/mex.warmer.service.ts
  src/endpoints/nfts/nft.module.ts
  src/endpoints/tokens/token.module.ts
  src/endpoints/transactions/transaction-action/recognizers/mex/transaction.action.mex.recognizer.module.ts
  src/graphql/entities/graphql.services.module.ts
  src/graphql/entities/xexchange/mex.token.module.ts
  src/graphql/entities/xexchange/mex.token/mex.token.resolver.ts
  src/main.ts
Labels: feature

#973 Proxify guardian data endpoint
  src/common/gateway/entities/gateway.component.request.ts
  src/endpoints/proxy/proxy.controller.ts
Labels: feature

#970 Integrate native auth v1
  config/config.devnet.yaml
  config/config.mainnet.yaml
  config/config.testnet.yaml
  package-lock.json
  package.json
  src/common/api-config/api.config.service.ts
  src/common/api-config/erdnest.config.service.impl.ts
  src/main.ts
  src/utils/jwt.or.native.auth.guard.ts
Labels: feature

#978 fix performance issue for auctions endpoint
  src/endpoints/marketplace/graphql/auctions.query.ts
  src/endpoints/marketplace/nft.marketplace.service.ts
Labels: performance

#979 More precision for node versions
  src/endpoints/nodes/node.service.ts
Labels: feature

#982 add filter by EGLD
  src/common/indexer/elastic/elastic.indexer.helper.ts
  src/endpoints/accounts/account.controller.ts
  src/test/integration/graphql/transactions.graph-spec.ts
  src/test/integration/services/transactions.e2e-spec.ts
Labels: feature

#980 Filter accounts by ownerAddress
  src/common/indexer/elastic/elastic.indexer.helper.ts
  src/common/indexer/elastic/elastic.indexer.service.ts
  src/common/indexer/entities/account.ts
  src/common/indexer/indexer.interface.ts
  src/common/indexer/indexer.service.ts
  src/common/indexer/postgres/entities/account.db.ts
  src/common/indexer/postgres/postgres.indexer.service.ts
  src/crons/cache.warmer/cache.warmer.service.ts
  src/crons/status.checker/status.checker.service.ts
  src/endpoints/accounts/account.controller.ts
  src/endpoints/accounts/account.service.ts
  src/endpoints/accounts/entities/account.filter.ts
  src/endpoints/accounts/entities/account.sort.ts
  src/endpoints/accounts/entities/account.ts
  src/endpoints/network/network.service.ts
  src/graphql/entities/account/account.input.ts
  src/graphql/entities/account/account.query.ts
  src/graphql/schema/schema.gql
  src/test/integration/graphql/accounts.graph-spec.ts
  src/test/integration/services/accounts.e2e-spec.ts
  src/test/integration/services/delegation.legacy.e2e-spec.ts
  src/test/integration/services/nodes.e2e-spec.ts
  src/test/unit/graphql/entities/account/account.query.spec.ts
  src/utils/cache.info.ts
Labels: feature

#983 expose transaction pool endpoint
  src/common/gateway/entities/gateway.component.request.ts
  src/common/gateway/entities/transaction.pool.ts
  src/endpoints/proxy/proxy.controller.ts
  src/endpoints/transactions/entities/transaction.pool.ts
Labels: feature

#986 Update SDK Nestjs to latest version
  package-lock.json
  package.json
  src/main.ts
Labels: bugfix

#987 Update SDK nestjs
  package-lock.json
  package.json
Labels: ignore-for-release
