Repository multiversx/mx-api-service, pull requests merged in 2024-03, with the labels that each got.

#1210 add shard controller spec
  src/test/unit/controllers/services.mock/shard.service.mock.ts
  src/test/unit/controllers/shard.controller.spec.ts
  src/test/unit/controllers/tags.controller.spec.ts
Labels: test

#1201 add support for token transfersCount
  src/common/indexer/elastic/elastic.indexer.helper.ts
  src/endpoints/tokens/entities/token.ts
  src/endpoints/tokens/token.module.ts
  src/endpoints/tokens/token.service.ts
  src/graphql/schema/schema.gql
  src/test/unit/services/tokens.spec.ts
  src/utils/cache.info.ts
Labels: feature

#1155 add epochsLeft key
  config/config.devnet-old.yaml
  config/config.devnet.yaml
  config/config.mainnet.yaml
  config/config.testnet.yaml
  src/common/api-config/api.config.service.ts
  src/common/gateway/entities/gateway.component.request.ts
  src/common/gateway/gateway.service.ts
  src/endpoints/nodes/entities/node.ts
  src/endpoints/nodes/node.service.ts
  src/graphql/schema/schema.gql
  src/test/mocks/nodes.mock.json
  src/test/unit/services/api.config.spec.ts
  src/test/unit/services/delegation.spec.ts
  src/test/unit/services/nodes.spec.ts
  src/test/unit/services/shards.spec.ts
  src/test/unit/services/stake.spec.ts
Labels: feature

#1217 add mexPairType token property
  src/endpoints/accounts/account.controller.ts
  src/endpoints/tokens/entities/token.detailed.ts
  src/endpoints/tokens/entities/token.filter.ts
  src/endpoints/tokens/entities/token.with.balance.ts
  src/endpoints/tokens/token.controller.ts
  src/endpoints/tokens/token.service.ts
  src/graphql/schema/schema.gql
  src/test/unit/services/tokens.spec.ts
Labels: feature

#1193 add more support for stakingV4
  config/config.testnet.yaml
  src/common/api-config/api.config.service.ts
  src/common/gateway/entities/auction.node.ts
  src/common/gateway/entities/auction.ts
  src/common/gateway/gateway.service.ts
  src/crons/cache.warmer/cache.warmer.service.ts
  src/endpoints/identities/entities/identity.sort.criteria.ts
  src/endpoints/identities/identities.controller.ts
  src/endpoints/identities/identities.service.ts
  src/endpoints/network/entities/economics.ts
  src/endpoints/network/network.service.ts
  src/endpoints/nodes/entities/node.filter.ts
  src/endpoints/nodes/entities/node.status.ts
  src/endpoints/nodes/entities/node.ts
  src/endpoints/nodes/entities/node.type.ts
  src/endpoints/nodes/node.controller.ts
  src/endpoints/nodes/node.service.ts
  src/endpoints/proxy/proxy.controller.ts
  src/endpoints/stake/entities/global.stake.ts
  src/endpoints/stake/entities/validator.info.result.ts
  src/endpoints/stake/stake.module.ts
  src/endpoints/stake/stake.service.ts
  src/graphql/schema/schema.gql
  src/test/mocks/identities.mock.json
  src/test/unit/controllers/network.controller.spec.ts
  src/test/unit/services/delegation.spec.ts
  src/test/unit/services/network.spec.ts
  src/test/unit/services/nodes.spec.ts
  src/test/unit/services/stake.spec.ts
Labels: feature

#1224 Update SDK-Nestjs to latest version
  package-lock.json
  package.json
Labels: ignore-for-release
