Repository multiversx/mx-api-service, pull requests merged in 2024-02, with the labels that each got.

#1192 add support for undefined for extract username raw base 64
  src/endpoints/usernames/username.utils.ts
Labels: bugfix

#1194 Deep history gateway integration
  config/config.e2e.mainnet.yaml
  config/config.mainnet.yaml
  config/config.testnet.yaml
  src/common/api-config/api.config.service.ts
  src/common/gateway/entities/gateway.component.request.ts
  src/common/gateway/gateway.service.ts
  src/common/indexer/elastic/elastic.indexer.service.ts
  src/common/indexer/indexer.interface.ts
  src/common/indexer/indexer.service.ts
  src/common/indexer/postgres/postgres.indexer.service.ts
  src/common/protocol/protocol.service.ts
  src/endpoints/accounts/account.controller.ts
  src/endpoints/accounts/account.service.ts
  src/endpoints/tokens/token.service.ts
  src/interceptors/deep-history.interceptor.ts
Labels: feature

#1197 Remove value from asyncCallbackEvent
  src/endpoints/transactions/transaction.get.service.ts
Labels: bugfix

#1199 Remove value from async callback event follow-up
  src/endpoints/transactions/transaction.get.service.ts
Labels: ignore-for-release

#1207 status checker initialize thresholds
  config/config.devnet.yaml
  config/config.mainnet.yaml
  config/config.testnet.yaml
  src/common/api-config/api.config.service.ts
  src/common/api-config/entities/status-checker-thresholds.ts
  src/crons/status.checker/status.checker.service.ts
Labels: refactoring
