Repository multiversx/mx-api-service, pull requests merged in 2024-01, with the labels that each got.

#1160 update to nestjs10 and latest nestjs-sdk 3.1.2
  package-lock.json
  package.json
  src/common/indexer/elastic/elastic.indexer.helper.ts
  src/common/indexer/elastic/elastic.indexer.service.ts
  src/main.ts
  src/queue.worker/nft.worker/nft.worker.module.ts
Labels: dependencies

#1172 apply isVerified property for a list of SC's
  src/crons/cache.warmer/cache.warmer.service.ts
  src/endpoints/accounts/account.service.ts
  src/endpoints/accounts/entities/account.detailed.ts
  src/endpoints/accounts/entities/account.ts
  src/utils/cache.info.ts
Labels: feature

#1171 update mexFarms / mexPairs with specific return types
  src/endpoints/mex/mex.controller.ts
Labels: refactoring

#1175 add generic proxy forward endpoint
  src/common/gateway/entities/gateway.component.request.ts
  src/endpoints/proxy/proxy.controller.ts
Labels: feature

#1174 add support for mex tokens previous price
  src/endpoints/mex/entities/mex.pair.ts
  src/endpoints/mex/entities/mex.token.ts
  src/endpoints/mex/mex.pair.service.ts
  src/endpoints/mex/mex.token.service.ts
Labels: feature

#1180 Identity owner fix
  src/common/keybase/keybase.service.ts
Labels: bugfix

#1181 Fix sharp dependency
  package-lock.json
  package.json
Labels: dependencies

#1170 add accounts ownerAssets key
  src/endpoints/accounts/account.controller.ts
  src/endpoints/accounts/account.service.ts
  src/endpoints/accounts/entities/account.filter.ts
  src/endpoints/accounts/entities/account.ts
  src/test/unit/services/accounts.spec.ts
Labels: feature

#1184 added sender and receiver usernames
  src/common/gateway/entities/transaction.ts
  src/common/indexer/entities/transaction.ts
  src/endpoints/transactions/entities/transaction.create.ts
  src/endpoints/transactions/entities/transaction.ts
  src/endpoints/transactions/transaction.get.service.ts
  src/endpoints/usernames/username.utils.ts
  src/test/unit/services/accounts.spec.ts
  src/test/unit/services/transactions.spec.ts
  src/test/unit/utils/username.utils.spec.ts
Labels: feature

#1168 include withContractExtraDetails on accounts endpoint
  src/common/indexer/elastic/elastic.indexer.helper.ts
  src/common/indexer/elastic/elastic.indexer.service.ts
  src/common/indexer/indexer.interface.ts
  src/common/indexer/indexer.service.ts
  src/crons/cache.warmer/cache.warmer.service.ts
  src/crons/status.checker/status.checker.service.ts
  src/endpoints/accounts/account.controller.ts
  src/endpoints/accounts/account.service.ts
  src/endpoints/accounts/entities/account.detailed.ts
  src/endpoints/accounts/entities/account.filter.ts
  src/endpoints/accounts/entities/account.query.options.ts
  src/endpoints/accounts/entities/account.ts
  src/endpoints/network/network.service.ts
  src/graphql/entities/account/account.input.ts
  src/graphql/entities/account/account.query.ts
  src/graphql/schema/schema.gql
  src/test/unit/services/accounts.spec.ts
  src/test/unit/services/transfers.spec.ts
Labels: feature

#1186 withTxCount, withScrCount support in account list endpoint
  src/common/indexer/elastic/elastic.indexer.helper.ts
  src/common/indexer/elastic/elastic.indexer.service.ts
  src/common/indexer/indexer.interface.ts
  src/common/indexer/indexer.service.ts
  src/crons/cache.warmer/cache.warmer.service.ts
  src/crons/status.checker/status.checker.service.ts
  src/endpoints/accounts/account.controller.ts
  src/endpoints/accounts/account.service.ts
  src/endpoints/accounts/entities/account.detailed.ts
  src/endpoints/accounts/entities/account.query.options.ts
  src/endpoints/accounts/entities/account.ts
  src/endpoints/network/network.service.ts
  src/graphql/entities/account/account.input.ts
  src/graphql/entities/account/account.query.ts
  src/graphql/schema/schema.gql
  src/test/unit/services/accounts.spec.ts
  src/test/unit/services/transfers.spec.ts
Labels: feature
