Repository multiversx/mx-api-service, pull requests merged in 2024-07, with the labels that each got.

#1286 Optimize elastic calls when fetching NFT name in transaction operations
  src/endpoints/tokens/token.transfer.service.ts
  src/endpoints/transactions/transaction.get.service.ts
  src/endpoints/transactions/transaction.service.ts
Labels: feature

#1289 Fix imports
  src/endpoints/tokens/token.transfer.service.ts
Labels: ignore-for-release

#1291 fetch ownerBelowRequiredBalanceThreshold from delegation providers
  src/endpoints/providers/entities/delegation.data.ts
  src/endpoints/providers/entities/provider.ts
  src/endpoints/providers/provider.service.ts
Labels: feature

#1251 add the nft processing queue name in configs
  config/config.devnet.yaml
  config/config.mainnet.yaml
  config/config.testnet.yaml
  src/common/api-config/api.config.service.ts
  src/main.ts
  src/queue.worker/nft.worker/nft.worker.module.ts
  src/queue.worker/nft.worker/nft.worker.service.ts
  src/queue.worker/nft.worker/queue/nft.queue.controller.ts
Labels: feature

#1293 Update token.transfer.service.ts
  src/endpoints/tokens/token.transfer.service.ts
Labels: feature

#1294 update sdk core to latest version
  package-lock.json
  package.json
Labels: dependencies
