Repository multiversx/mx-api-service, pull requests merged in 2024-09, with the labels that each got.

#1290 fetch token price from mx-assets priceSource.url
  src/common/assets/entities/token.assets.price.source.ts
  src/common/assets/entities/token.assets.price.source.type.ts
  src/endpoints/tokens/token.service.ts
  src/test/unit/services/tokens.spec.ts
Labels: feature

#1306 Nodes and tokens fetch from external api
  config/config.devnet.yaml
  config/config.mainnet.yaml
  config/config.testnet.yaml
  docker-compose.yml
  src/common/api-config/api.config.service.ts
  src/endpoints/nodes/node.service.ts
  src/endpoints/tokens/token.service.ts
  src/test/unit/services/nodes.spec.ts
  src/test/unit/services/tokens.spec.ts
Labels: feature

#1323 Default features disabled
  config/config.devnet.yaml
  config/config.mainnet.yaml
  config/config.testnet.yaml
Labels: ignore-for-release

#1321 add applications unit tests
  src/graphql/schema/schema.gql
  src/test/unit/services/applications.spec.ts
Labels: test

#1309 Integration of K6 into API Github workflow
  .github/workflows/load-tests.yml
  k6/.gitignore
  k6/compare-results.js
  k6/output/.gitkeep
  k6/preload.js
  k6/script.js
Labels: feature

#1326 Fetch-providers-from-external-API
  config/config.devnet.yaml
  config/config.mainnet.yaml
  config/config.testnet.yaml
  src/common/api-config/api.config.service.ts
  src/endpoints/providers/provider.service.ts
  src/test/unit/services/providers.spec.ts
Labels: feature, test

#1330 nodes fetch from external api unit tests
  src/test/unit/services/nodes.spec.ts
Labels: test

#1332 Filter NFTs by full tag
  src/common/indexer/elastic/elastic.indexer.helper.ts
Labels: bugfix

#1337 Remove unnecessary file
  erl_crash.dump
Labels: ignore-for-release

#1338 Handle activation epoch where staking v4 flag is checked
  src/crons/cache.warmer/cache.warmer.service.ts
  src/endpoints/network/network.service.ts
  src/endpoints/nodes/node.service.ts
  src/test/unit/services/nodes.spec.ts
Labels: bugfix

#1324 remove support for indexer v 3
  config/config.devnet-old.yaml
  config/config.devnet.yaml
  config/config.e2e-mocked.mainnet.yaml
  config/config.e2e.mainnet.yaml
  config/config.mainnet.yaml
  config/config.testnet.yaml
  src/common/api-config/api.config.service.ts
  src/common/indexer/elastic/elastic.indexer.helper.ts
  src/common/indexer/elastic/elastic.indexer.service.ts
  src/endpoints/accounts/account.controller.ts
  src/endpoints/accounts/account.service.ts
  src/endpoints/collections/collection.service.ts
  src/endpoints/esdt/esdt.address.service.ts
  src/endpoints/esdt/esdt.service.ts
  src/endpoints/nfts/nft.service.ts
  src/endpoints/tokens/token.controller.ts
  src/endpoints/tokens/token.service.ts
  src/graphql/entities/transfers/transfers.query.ts
  src/graphql/schema/schema.gql
  src/main.ts
  src/test/unit/services/accounts.spec.ts
  src/test/unit/services/api.config.spec.ts
  src/test/unit/services/esdt.address.spec.ts
Labels: refactoring

#1342 add support for token priceSource filter
  src/endpoints/tokens/entities/token.filter.ts
  src/endpoints/tokens/token.controller.ts
  src/endpoints/tokens/token.service.ts
Labels: feature

#1334 add mex token charts
  src/endpoints/mex/entities/mex.token.chart.ts
  src/endpoints/mex/mex.controller.ts
  src/endpoints/mex/mex.module.ts
  src/endpoints/mex/mex.token.charts.service.ts
  src/test/unit/services/mex.token.charts.spec.ts
  src/utils/cache.info.ts
Labels: feature, test

#1335 update deprecated pairs query
  src/endpoints/mex/entities/mex.pair.status.ts
  src/endpoints/mex/entities/mex.pair.ts
  src/endpoints/mex/mex.pair.service.ts
Labels: refactoring
