Repository multiversx/mx-api-service, pull requests merged in 2024-05, with the labels that each got.

#1246 add provider delegators
  src/common/indexer/elastic/elastic.indexer.service.ts
  src/common/indexer/entities/provider.delegators.ts
  src/common/indexer/indexer.interface.ts
  src/common/indexer/indexer.service.ts
  src/common/indexer/postgres/postgres.indexer.service.ts
  src/endpoints/providers/entities/provider.accounts.ts
  src/endpoints/providers/provider.controller.ts
  src/endpoints/providers/provider.service.ts
  src/test/unit/services/providers.spec.ts
Labels: feature

#1242 add lowLiquidityThresholdPercent property
  src/endpoints/tokens/entities/token.ts
  src/endpoints/tokens/token.service.ts
  src/graphql/schema/schema.gql
Labels: feature

#1243 add latest sdk-nestjs version
  package-lock.json
  package.json
Labels: dependencies

#1245 Transfers last 24 h for applications
  config/config.devnet.yaml
  config/config.mainnet.yaml
  config/config.testnet.yaml
  src/common/api-config/api.config.service.ts
  src/common/indexer/elastic/elastic.indexer.helper.ts
  src/common/indexer/elastic/elastic.indexer.service.ts
  src/common/indexer/entities/account.ts
  src/common/indexer/indexer.interface.ts
  src/common/indexer/indexer.service.ts
  src/common/indexer/postgres/postgres.indexer.service.ts
  src/crons/cache.warmer/cache.warmer.service.ts
  src/endpoints/accounts/account.service.ts
  src/endpoints/accounts/entities/account.query.options.ts
  src/endpoints/accounts/entities/account.sort.ts
  src/endpoints/accounts/entities/account.ts
  src/endpoints/accounts/entities/application.most.used.ts
  src/graphql/schema/schema.gql
  src/test/unit/services/accounts.spec.ts
  src/utils/cache.info.ts
Labels: feature

#1188 add support for assets in ES
  config/config.mainnet.yaml
  src/common/api-config/api.config.service.ts
  src/common/indexer/elastic/elastic.indexer.helper.ts
  src/common/indexer/elastic/elastic.indexer.service.ts
  src/common/indexer/entities/account.ts
  src/common/indexer/entities/not.writable.error.ts
  src/common/indexer/indexer.interface.ts
  src/common/indexer/indexer.service.ts
  src/common/indexer/postgres/postgres.indexer.service.ts
  src/crons/cache.warmer/cache.warmer.service.ts
  src/endpoints/accounts/account.controller.ts
  src/endpoints/accounts/account.service.ts
  src/endpoints/accounts/entities/account.query.options.ts
  src/main.ts
Labels: feature

#1241 add nodes feature requests
  src/endpoints/nodes/entities/node.auction.filter.ts
  src/endpoints/nodes/entities/node.auction.ts
  src/endpoints/nodes/entities/node.filter.ts
  src/endpoints/nodes/entities/node.sort.auction.ts
  src/endpoints/nodes/entities/node.sort.ts
  src/endpoints/nodes/entities/node.ts
  src/endpoints/nodes/node.controller.ts
  src/endpoints/nodes/node.module.ts
  src/endpoints/nodes/node.service.ts
  src/endpoints/stake/entities/global.stake.ts
  src/endpoints/stake/stake.service.ts
  src/graphql/schema/schema.gql
  src/test/mocks/nodes.mock.json
  src/test/unit/services/delegation.spec.ts
  src/test/unit/services/nodes.spec.ts
  src/test/unit/services/shards.spec.ts
  src/test/unit/services/stake.spec.ts
Labels: feature, refactoring

#1254 TPS Support
  config/config.devnet.yaml
  config/config.mainnet.yaml
  config/config.testnet.yaml
  src/common/api-config/api.config.service.ts
  src/common/gateway/gateway.service.ts
  src/crons/cache.warmer/cache.warmer.module.ts
  src/crons/tps/tps-warmer.service.ts
  src/endpoints/endpoints.controllers.module.ts
  src/endpoints/endpoints.services.module.ts
  src/endpoints/tps/entities/tps.frequency.ts
  src/endpoints/tps/entities/tps.interval.ts
  src/endpoints/tps/entities/tps.ts
  src/endpoints/tps/tps.controller.ts
  src/endpoints/tps/tps.module.ts
  src/endpoints/tps/tps.service.ts
  src/test/unit/services/tps.spec.ts
  src/utils/cache.info.ts
  src/utils/tps.utils.ts
Labels: feature

#1250 add default icons for exchange contracts
  src/common/assets/assets.service.ts
Labels: feature, refactoring

#1255 Stakingv4 preparations
  config/config.devnet.yaml
  config/config.mainnet.yaml
  src/crons/cache.warmer/cache.warmer.service.ts
  src/endpoints/nodes/node.service.ts
  src/endpoints/shards/shard.service.ts
  src/endpoints/stake/stake.service.ts
  src/test/unit/services/stake.spec.ts
  src/utils/cache.info.ts
Labels: feature

#1260 Staking v4 improvements
  src/crons/cache.warmer/cache.warmer.service.ts
  src/endpoints/nodes/node.service.ts
  src/endpoints/stake/stake.service.ts
  src/test/unit/services/stake.spec.ts
Labels: feature

#1259 TPS max and total tx count
  src/common/indexer/elastic/elastic.indexer.helper.ts
  src/crons/tps/tps-warmer.service.ts
  src/endpoints/blocks/entities/block.filter.ts
  src/endpoints/tps/tps.controller.ts
  src/endpoints/tps/tps.service.ts
  src/utils/cache.info.ts
Labels: feature

#1262 Validator auction query fixes
  src/endpoints/identities/entities/stake.info.ts
  src/endpoints/identities/identities.module.ts
  src/endpoints/identities/identities.service.ts
  src/endpoints/nodes/node.service.ts
  src/endpoints/stake/stake.service.ts
  src/utils/cache.info.ts
Labels: bugfix

#1267 Default pagination for auction list
  src/endpoints/nodes/node.controller.ts
Labels: feature

#1266 add applications endpoints
  src/common/indexer/elastic/elastic.indexer.helper.ts
  src/common/indexer/elastic/elastic.indexer.service.ts
  src/common/indexer/indexer.interface.ts
  src/common/indexer/indexer.service.ts
  src/common/indexer/postgres/postgres.indexer.service.ts
  src/crons/elastic.updater/elastic.updater.service.ts
  src/endpoints/applications/application.controller.ts
  src/endpoints/applications/application.module.ts
  src/endpoints/applications/application.service.ts
  src/endpoints/applications/entities/application.filter.ts
  src/endpoints/applications/entities/application.ts
  src/endpoints/endpoints.controllers.module.ts
  src/endpoints/endpoints.services.module.ts
  src/graphql/schema/schema.gql
  src/utils/cache.info.ts
Labels: feature

#1265 add node waiting epochs left proxy
  src/endpoints/proxy/gateway.proxy.controller.ts
Labels: feature

#1270 fix missing stake test mock
  src/endpoints/identities/identities.service.ts
  src/test/unit/services/stake.spec.ts
Labels: test

#1271 Revert additional farm info PR
  src/endpoints/mex/entities/mex.pair.ts
  src/endpoints/mex/entities/mex.pairs..filter.ts
  src/endpoints/mex/mex.controller.ts
  src/endpoints/mex/mex.pair.service.ts
  src/graphql/entities/xexchange/mex.pairs/mex.pairs.query.ts
  src/test/unit/controllers/mex.controller.spec.ts
Labels: ignore-for-release

#1269 Improved caching for validator auctions
  src/common/indexer/elastic/elastic.indexer.service.ts
  src/endpoints/nodes/node.service.ts
  src/endpoints/proxy/gateway.proxy.controller.ts
Labels: feature

#1272 Load smart contract result in transaction endpoint, do not fail if esdt loading failed
  src/common/indexer/elastic/elastic.indexer.service.ts
  src/endpoints/esdt/esdt.service.ts
  src/endpoints/sc-results/scresult.service.ts
Labels: feature

#1276 Add mex-pairs endpoint
  src/endpoints/mex/mex.controller.ts
Labels: feature
